
; [mysql本地]
mysql_hostname     =127.0.0.1
mysql_port         = 3306
mysql_user         = root
mysql_pass         = shx19930509321
mysql_databasename = payflow

;日志配置
;[logconf]
log_maxAge       = 365 ;//日志最大保存时间（天）
log_rotationTime = 24  ;//日志切割时间间隔（小时）
log_rotationCount = 5  ;//
log_rotationSize = 1000000000;   ;//10M[10485760] 日志切割时间间隔（["104857600" //100M] ["1048576" //1M] ["102400" //100K] ["1024" //1KB]    1kB ）
log_Path         = "./log"
log_FileName     = "vehicleLicensePlateRecognition.log"

;[redis开发]
redis_addr          = "192.168.200.204:6379"
redis_databasename  = 2

;[ip_address]结算监控6089 运维管理6077 车牌识别6066
ip_address          =192.168.200.204:6066

;1.前置机抓拍信息上传接口 http://172.31.49.252/data-collect/report/frontend
gwCaptureInformationUpload_ip_address = http://172.31.49.252/data-collect/report/frontend

;2.获取token
get_token=http://172.31.49.252/processor-control/collect/token/

;3.根据token获取camera列表
get_camera_list=http://172.31.49.252/processor-control/collect/cameras/

;oss存储配置


；用户登陆
user_name       =admin
password        =admin

